# Generated by Django 4.0.1 on 2022-01-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_userprofile_skill_project_experince_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experince',
            name='present',
        ),
    ]
